version: '3.8'

services:
  payment-service:
    image: truongikpk/bookstore-payment-service:v1.0.0
    container_name: payment-service
    ports:
      - "8085:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - bookstore-network

networks:
  bookstore-network:
    external: true
